package bus

import "github.com/gojargo/jargo/frames"

// Types is the registry every built-in bus message and frame is registered
// in, and the one a serializer uses unless it is given another.
//
// A type registers under its own name, without its package, because that name
// is all the far end has to go on. Registering here is what makes a value
// able to cross a bus that leaves the process: anything not registered is
// refused on arrival rather than silently arriving as something else.
//
// Register a type of your own with Types.Register at startup.
//
//nolint:gochecknoglobals // the process-wide registry, written once at init
var Types = NewTypeRegistry()

//nolint:gochecknoinits,funlen // one registration per type that may cross a bus
func init() {
	// The conversation and its toolset, which travel through adapters rather
	// than by their fields.
	Types.Register("LLMContext", &frames.LLMContext{})
	Types.Register("ToolsSchema", &frames.ToolsSchema{})

	// The bus's own messages.
	Types.Register("FrameMessage", &FrameMessage{})
	Types.Register("TTSSpeakMessage", &TTSSpeakMessage{})
	Types.Register("FlushProgressMessage", &FlushProgressMessage{})
	Types.Register("ActivateWorkerMessage", &ActivateWorkerMessage{})
	Types.Register("DeactivateWorkerMessage", &DeactivateWorkerMessage{})
	Types.Register("EndMessage", &EndMessage{})
	Types.Register("EndWorkerMessage", &EndWorkerMessage{})
	Types.Register("CancelMessage", &CancelMessage{})
	Types.Register("CancelWorkerMessage", &CancelWorkerMessage{})
	Types.Register("AddWorkerMessage", &AddWorkerMessage{})
	Types.Register("WorkerRegistryMessage", &WorkerRegistryMessage{})
	Types.Register("WorkerReadyMessage", &WorkerReadyMessage{})
	Types.Register("WorkerErrorMessage", &WorkerErrorMessage{})
	Types.Register("WorkerLocalErrorMessage", &WorkerLocalErrorMessage{})
	Types.Register("JobRequestMessage", &JobRequestMessage{})
	Types.Register("JobResponseMessage", &JobResponseMessage{})
	Types.Register("JobResponseUrgentMessage", &JobResponseUrgentMessage{})
	Types.Register("JobUpdateMessage", &JobUpdateMessage{})
	Types.Register("JobUpdateUrgentMessage", &JobUpdateUrgentMessage{})
	Types.Register("JobUpdateRequestMessage", &JobUpdateRequestMessage{})
	Types.Register("JobCancelMessage", &JobCancelMessage{})
	Types.Register("JobStreamStartMessage", &JobStreamStartMessage{})
	Types.Register("JobStreamDataMessage", &JobStreamDataMessage{})
	Types.Register("JobStreamEndMessage", &JobStreamEndMessage{})

	// Every frame, since a bridged worker may be handed any of them.
	Types.Register("AggregatedTextFrame", &frames.AggregatedTextFrame{})
	Types.Register("AggregatedTextProgressFrame", &frames.AggregatedTextProgressFrame{})
	Types.Register("AudioBufferStartRecordingFrame", &frames.AudioBufferStartRecordingFrame{})
	Types.Register("AudioBufferStopRecordingFrame", &frames.AudioBufferStopRecordingFrame{})
	Types.Register("BotConnectedFrame", &frames.BotConnectedFrame{})
	Types.Register("BotSpeakingFrame", &frames.BotSpeakingFrame{})
	Types.Register("BotStartedSpeakingFrame", &frames.BotStartedSpeakingFrame{})
	Types.Register("BotStoppedSpeakingFrame", &frames.BotStoppedSpeakingFrame{})
	Types.Register("CancelFrame", &frames.CancelFrame{})
	Types.Register("CancelWorkerFrame", &frames.CancelWorkerFrame{})
	Types.Register("ClientConnectedFrame", &frames.ClientConnectedFrame{})
	Types.Register("EndFrame", &frames.EndFrame{})
	Types.Register("EndWorkerFrame", &frames.EndWorkerFrame{})
	Types.Register("ErrorFrame", &frames.ErrorFrame{})
	Types.Register("FatalErrorFrame", &frames.FatalErrorFrame{})
	Types.Register("FilterEnableFrame", &frames.FilterEnableFrame{})
	Types.Register("FilterUpdateSettingsFrame", &frames.FilterUpdateSettingsFrame{})
	Types.Register("FrameProcessorPauseFrame", &frames.FrameProcessorPauseFrame{})
	Types.Register("FrameProcessorPauseUrgentFrame", &frames.FrameProcessorPauseUrgentFrame{})
	Types.Register("FrameProcessorResumeFrame", &frames.FrameProcessorResumeFrame{})
	Types.Register("FrameProcessorResumeUrgentFrame", &frames.FrameProcessorResumeUrgentFrame{})
	Types.Register("FunctionCallCancelFrame", &frames.FunctionCallCancelFrame{})
	Types.Register("FunctionCallInProgressFrame", &frames.FunctionCallInProgressFrame{})
	Types.Register("FunctionCallResultFrame", &frames.FunctionCallResultFrame{})
	Types.Register("FunctionCallsStartedFrame", &frames.FunctionCallsStartedFrame{})
	Types.Register("HeartbeatFrame", &frames.HeartbeatFrame{})
	Types.Register("InputAudioRawFrame", &frames.InputAudioRawFrame{})
	Types.Register("InputDTMFFrame", &frames.InputDTMFFrame{})
	Types.Register("InputTextRawFrame", &frames.InputTextRawFrame{})
	Types.Register("InputTransportMessageFrame", &frames.InputTransportMessageFrame{})
	Types.Register("InputTransportStartAudioStreamingFrame", &frames.InputTransportStartAudioStreamingFrame{})
	Types.Register("InterimTranscriptionFrame", &frames.InterimTranscriptionFrame{})
	Types.Register("InterruptionFrame", &frames.InterruptionFrame{})
	Types.Register("InterruptionWorkerFrame", &frames.InterruptionWorkerFrame{})
	Types.Register("LLMAssistantPushAggregationFrame", &frames.LLMAssistantPushAggregationFrame{})
	Types.Register("LLMConfigureOutputFrame", &frames.LLMConfigureOutputFrame{})
	Types.Register("LLMContextAssistantTimestampFrame", &frames.LLMContextAssistantTimestampFrame{})
	Types.Register("LLMContextAssistantTurnFrame", &frames.LLMContextAssistantTurnFrame{})
	Types.Register("LLMContextFrame", &frames.LLMContextFrame{})
	Types.Register("LLMContextSummaryRequestFrame", &frames.LLMContextSummaryRequestFrame{})
	Types.Register("LLMContextSummaryResultFrame", &frames.LLMContextSummaryResultFrame{})
	Types.Register("LLMEnablePromptCachingFrame", &frames.LLMEnablePromptCachingFrame{})
	Types.Register("LLMFullResponseEndFrame", &frames.LLMFullResponseEndFrame{})
	Types.Register("LLMFullResponseStartFrame", &frames.LLMFullResponseStartFrame{})
	Types.Register("LLMMarkerFrame", &frames.LLMMarkerFrame{})
	Types.Register("LLMMessagesAppendFrame", &frames.LLMMessagesAppendFrame{})
	Types.Register("LLMMessagesTransformFrame", &frames.LLMMessagesTransformFrame{})
	Types.Register("LLMMessagesUpdateFrame", &frames.LLMMessagesUpdateFrame{})
	Types.Register("LLMRunFrame", &frames.LLMRunFrame{})
	Types.Register("LLMServiceMetadataFrame", &frames.LLMServiceMetadataFrame{})
	Types.Register("LLMSetToolChoiceFrame", &frames.LLMSetToolChoiceFrame{})
	Types.Register("LLMSetToolsFrame", &frames.LLMSetToolsFrame{})
	Types.Register("LLMSummarizeContextFrame", &frames.LLMSummarizeContextFrame{})
	Types.Register("LLMTextFrame", &frames.LLMTextFrame{})
	Types.Register("LLMThoughtEndFrame", &frames.LLMThoughtEndFrame{})
	Types.Register("LLMThoughtStartFrame", &frames.LLMThoughtStartFrame{})
	Types.Register("LLMThoughtTextFrame", &frames.LLMThoughtTextFrame{})
	Types.Register("LLMUpdateSettingsFrame", &frames.LLMUpdateSettingsFrame{})
	Types.Register("ManuallySwitchServiceFrame", &frames.ManuallySwitchServiceFrame{})
	Types.Register("MetricsFrame", &frames.MetricsFrame{})
	Types.Register("MixerEnableFrame", &frames.MixerEnableFrame{})
	Types.Register("MixerUpdateSettingsFrame", &frames.MixerUpdateSettingsFrame{})
	Types.Register("OutputAudioRawFrame", &frames.OutputAudioRawFrame{})
	Types.Register("OutputDTMFFrame", &frames.OutputDTMFFrame{})
	Types.Register("OutputDTMFUrgentFrame", &frames.OutputDTMFUrgentFrame{})
	Types.Register("OutputTransportMessageFrame", &frames.OutputTransportMessageFrame{})
	Types.Register("OutputTransportMessageUrgentFrame", &frames.OutputTransportMessageUrgentFrame{})
	Types.Register("OutputTransportReadyFrame", &frames.OutputTransportReadyFrame{})
	Types.Register("PipelineFlushFrame", &frames.PipelineFlushFrame{})
	Types.Register("ProposedUserStartedSpeakingFrame", &frames.ProposedUserStartedSpeakingFrame{})
	Types.Register("ProposedUserStoppedSpeakingFrame", &frames.ProposedUserStoppedSpeakingFrame{})
	Types.Register("STTMetadataFrame", &frames.STTMetadataFrame{})
	Types.Register("STTMuteFrame", &frames.STTMuteFrame{})
	Types.Register("STTUpdateSettingsFrame", &frames.STTUpdateSettingsFrame{})
	Types.Register("ServiceMetadataFrame", &frames.ServiceMetadataFrame{})
	Types.Register("ServiceSwitcherRequestMetadataFrame", &frames.ServiceSwitcherRequestMetadataFrame{})
	Types.Register("ServiceUpdateSettingsFrame", &frames.ServiceUpdateSettingsFrame{})
	Types.Register("SpeechControlParamsFrame", &frames.SpeechControlParamsFrame{})
	Types.Register("SpeechOutputAudioRawFrame", &frames.SpeechOutputAudioRawFrame{})
	Types.Register("StartFrame", &frames.StartFrame{})
	Types.Register("StopFrame", &frames.StopFrame{})
	Types.Register("StopWorkerFrame", &frames.StopWorkerFrame{})
	Types.Register("TTSAudioRawFrame", &frames.TTSAudioRawFrame{})
	Types.Register("TTSSpeakFrame", &frames.TTSSpeakFrame{})
	Types.Register("TTSStartedFrame", &frames.TTSStartedFrame{})
	Types.Register("TTSStoppedFrame", &frames.TTSStoppedFrame{})
	Types.Register("TTSTextFrame", &frames.TTSTextFrame{})
	Types.Register("TTSUpdateSettingsFrame", &frames.TTSUpdateSettingsFrame{})
	Types.Register("TextFrame", &frames.TextFrame{})
	Types.Register("TranscriptionFrame", &frames.TranscriptionFrame{})
	Types.Register("TranslationFrame", &frames.TranslationFrame{})
	Types.Register("UserAudioRawFrame", &frames.UserAudioRawFrame{})
	Types.Register("UserIdleTimeoutUpdateFrame", &frames.UserIdleTimeoutUpdateFrame{})
	Types.Register("UserMuteStartedFrame", &frames.UserMuteStartedFrame{})
	Types.Register("UserMuteStoppedFrame", &frames.UserMuteStoppedFrame{})
	Types.Register("UserSpeakingFrame", &frames.UserSpeakingFrame{})
	Types.Register("UserStartedSpeakingFrame", &frames.UserStartedSpeakingFrame{})
	Types.Register("UserStoppedSpeakingFrame", &frames.UserStoppedSpeakingFrame{})
	Types.Register("UserTurnInferenceCompletedFrame", &frames.UserTurnInferenceCompletedFrame{})
	Types.Register("VADParamsUpdateFrame", &frames.VADParamsUpdateFrame{})
	Types.Register("VADUserStartedSpeakingFrame", &frames.VADUserStartedSpeakingFrame{})
	Types.Register("VADUserStoppedSpeakingFrame", &frames.VADUserStoppedSpeakingFrame{})
}
