package sentencex

import "sync"

// languageFallback is one entry of the fallback chain table: the languages to
// try, in order, when there are no rules for code.
type languageFallback struct {
	code      string
	fallbacks []string
}

// languageFallbacks maps a language code to its fallback chain.
//
//nolint:gochecknoglobals,goconst // fixed lookup table of language codes
var languageFallbacks = []languageFallback{
	{"aae", []string{"it"}},
	{"ab", []string{"ru"}},
	{"abs", []string{"id"}},
	{"ace", []string{"id"}},
	{"acm", []string{"ar"}},
	{"ady", []string{"ady-cyrl"}},
	{"aeb", []string{"aeb-arab"}},
	{"aeb-arab", []string{"ar"}},
	{"aln", []string{"sq"}},
	// Not so standard: als is supposed to be Tosk Albanian,
	// but in Wikipedia it's used for a Germanic language.
	// Use 'gsw' instead. See T25215.
	{"als", []string{"gsw", "de"}},
	{"alt", []string{"ru"}},
	{"ami", []string{"zh-tw", "zh-hant", "zh", "zh-hans"}},
	{"an", []string{"es"}},
	{"anp", []string{"hi"}},
	{"apc", []string{"ar"}},
	{"arn", []string{"es"}},
	{"arq", []string{"ar"}},
	{"ary", []string{"ar"}},
	{"arz", []string{"ar"}},
	{"ast", []string{"es"}},
	{"atj", []string{"fr"}},
	{"av", []string{"ru"}},
	{"avk", []string{"fr", "es", "ru"}},
	{"awa", []string{"hi"}},
	{"ay", []string{"es"}},
	{"azb", []string{"fa"}},
	{"ba", []string{"ru"}},
	{"ban", []string{"id"}},
	{"ban-bali", []string{"ban"}},
	{"bar", []string{"de"}},
	// Deprecated: Use 'sgs' instead. See T27522.
	{"bat-smg", []string{"sgs", "lt"}},
	{"bbc", []string{"bbc-latn"}},
	{"bbc-latn", []string{"id"}},
	{"bcc", []string{"fa"}},
	{"bci", []string{"fr"}},
	{"bdr", []string{"ms"}},
	{"be-tarask", []string{"be"}},
	// Deprecated: Use 'be-tarask' instead. See T11823.
	{"be-x-old", []string{"be-tarask", "be"}},
	{"bew", []string{"id"}},
	{"bgn", []string{"fa"}},
	{"bh", []string{"bho"}},
	{"bjn", []string{"id"}},
	{"blk", []string{"my"}},
	{"bm", []string{"fr"}},
	{"bpy", []string{"bn"}},
	{"bqi", []string{"fa"}},
	{"btm", []string{"id"}},
	{"bug", []string{"id"}},
	{"bug-bugi", []string{"bug", "id"}},
	{"bxr", []string{"ru"}},
	{"ca", []string{"oc"}},
	{"cbk-zam", []string{"es"}},
	{"cdo", []string{"cdo-latn", "cdo-hant", "nan-hant", "zh-hant", "zh", "zh-hans"}},
	{"cdo-hant", []string{"cdo", "cdo-latn", "nan-hant", "zh-hant", "zh", "zh-hans"}},
	{"cdo-latn", []string{"cdo", "cdo-hant", "nan-hant", "zh-hant", "zh", "zh-hans"}},
	{"ce", []string{"ru"}},
	{"co", []string{"it"}},
	{"cpx", []string{"cpx-hant", "cpx-hans", "cpx-latn", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"cpx-hans", []string{"cpx", "cpx-hant", "cpx-latn", "cdo", "zh-hans", "zh", "zh-hant"}},
	{"cpx-hant", []string{"cpx", "cpx-hans", "cpx-latn", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"crh", []string{"crh-latn", "tr"}},
	{"crh-cyrl", []string{"tr"}},
	{"crh-latn", []string{"tr"}},
	{"cs", []string{"sk"}},
	{"csb", []string{"pl"}},
	{"cv", []string{"ru"}},
	{"de-at", []string{"de"}},
	{"de-ch", []string{"de"}},
	{"de-formal", []string{"de"}},
	{"dsb", []string{"hsb", "de"}},
	{"dtp", []string{"ms"}},
	{"dty", []string{"ne"}},
	{"dua", []string{"fr"}},
	{"egl", []string{"it"}},
	{"eml", []string{"it"}},
	{"es-formal", []string{"es"}},
	{"ext", []string{"es"}},
	{"fit", []string{"fi"}},
	// Deprecated: Use 'vro' instead. See T31186.
	{"fiu-vro", []string{"vro", "et"}},
	{"fon", []string{"fr"}},
	{"frc", []string{"fr"}},
	{"frp", []string{"fr"}},
	{"frr", []string{"de"}},
	{"fur", []string{"it"}},
	{"gag", []string{"tr"}},
	{"gan", []string{"gan-hant", "gan-hans", "zh-hant", "zh", "zh-hans"}},
	{"gan-hans", []string{"gan", "gan-hant", "zh-hans", "zh", "zh-hant"}},
	{"gan-hant", []string{"gan", "gan-hans", "zh-hant", "zh", "zh-hans"}},
	{"gcf", []string{"fr"}},
	{"gcr", []string{"fr"}},
	{"gl", []string{"pt"}},
	{"gld", []string{"ru"}},
	{"glk", []string{"fa"}},
	{"gn", []string{"es"}},
	{"gom", []string{"gom-deva", "gom-latn"}},
	{"gom-deva", []string{"gom-latn"}},
	{"gor", []string{"id"}},
	{"gsw", []string{"de"}},
	{"guc", []string{"es"}},
	{"hak", []string{"zh-hant", "zh", "zh-hans"}},
	{"hif", []string{"hif-latn"}},
	{"hke", []string{"fr"}},
	{"hrx", []string{"de"}},
	{"hsb", []string{"dsb", "de"}},
	{"hsn", []string{"zh-hant", "zh", "zh-hans"}},
	{"ht", []string{"fr"}},
	{"hu-formal", []string{"hu"}},
	{"hyw", []string{"hy"}},
	{"iba", []string{"ms"}},
	{"ii", []string{"zh-cn", "zh-hans", "zh", "zh-hant"}},
	{"ike-cans", []string{"iu"}},
	{"ike-latn", []string{"iu"}},
	{"inh", []string{"ru"}},
	{"io", []string{"eo"}},
	{"iu", []string{"ike-cans"}},
	{"jut", []string{"da"}},
	{"jv", []string{"id"}},
	{"kaa", []string{"kk-latn", "kk-cyrl"}},
	{"kab", []string{"fr"}},
	{"kbd", []string{"kbd-cyrl"}},
	{"kbp", []string{"fr"}},
	{"kea", []string{"pt"}},
	{"kge", []string{"id"}},
	{"khw", []string{"ur"}},
	{"kiu", []string{"tr"}},
	{"kjh", []string{"ru"}},
	{"kjp", []string{"my"}},
	{"kk", []string{"kk-cyrl"}},
	{"kk-arab", []string{"kk", "kk-cyrl"}},
	{"kk-cn", []string{"kk-arab", "kk", "kk-cyrl"}},
	{"kk-cyrl", []string{"kk"}},
	{"kk-kz", []string{"kk-cyrl", "kk"}},
	{"kk-latn", []string{"kk", "kk-cyrl"}},
	{"kk-tr", []string{"kk-latn", "kk", "kk-cyrl"}},
	{"kl", []string{"da"}},
	{"ko-kp", []string{"ko"}},
	{"koi", []string{"ru"}},
	{"kr", []string{"knc"}},
	{"krc", []string{"ru"}},
	{"krl", []string{"fi"}},
	{"ks", []string{"ks-arab"}},
	{"ksh", []string{"de"}},
	{"ksw", []string{"my"}},
	{"ku", []string{"ku-latn"}},
	{"ku-arab", []string{"ku", "ckb"}},
	{"ku-latn", []string{"ku"}},
	{"kum", []string{"ru"}},
	{"kv", []string{"ru"}},
	{"lad", []string{"es"}},
	{"lb", []string{"de"}},
	{"lbe", []string{"ru"}},
	{"lez", []string{"ru", "az"}},
	{"li", []string{"nl"}},
	{"lij", []string{"it"}},
	{"liv", []string{"et"}},
	{"ljp", []string{"id"}},
	{"lki", []string{"fa"}},
	{"lld", []string{"it", "rm", "fur"}},
	{"lmo", []string{"pms", "eml", "lij", "vec", "it"}},
	{"ln", []string{"fr"}},
	{"lrc", []string{"fa"}},
	{"ltg", []string{"lv"}},
	{"lua", []string{"fr"}},
	{"luz", []string{"fa"}},
	{"lzh", []string{"zh-hant", "zh", "zh-hans"}},
	{"lzz", []string{"tr"}},
	{"mad", []string{"id"}},
	{"mag", []string{"hi"}},
	{"mai", []string{"hi"}},
	{"map-bms", []string{"jv", "id"}},
	{"mdf", []string{"myv", "ru"}},
	{"mg", []string{"fr"}},
	{"mhr", []string{"mrj", "ru"}},
	{"min", []string{"id"}},
	{"mnc-latn", []string{"mnc"}},
	{"mnc-mong", []string{"mnc"}},
	{"mnw", []string{"my"}},
	{"mo", []string{"ro"}},
	{"mrj", []string{"mhr", "ru"}},
	{"ms-arab", []string{"ms"}},
	{"mui", []string{"id"}},
	{"mwl", []string{"pt"}},
	{"myv", []string{"mdf", "ru"}},
	{"mzn", []string{"fa"}},
	{"nah", []string{"es"}},
	{"nan", []string{"nan-latn-pehoeji", "nan-latn-tailo", "nan-hant", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"nan-hant", []string{"nan", "nan-latn-pehoeji", "nan-latn-tailo", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"nan-latn-pehoeji", []string{"nan-latn", "nan-latn-tailo", "nan", "nan-hant", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"nan-latn-tailo", []string{"nan-latn", "nan-latn-pehoeji", "nan", "nan-hant", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"nap", []string{"it"}},
	{"nb", []string{"no", "nn"}},
	{"nds", []string{"de"}},
	{"nds-nl", []string{"nl"}},
	{"nia", []string{"id"}},
	{"nl-informal", []string{"nl"}},
	{"nn", []string{"no", "nb"}},
	// Deprecated: Use 'nb' or 'nn' instead.
	{"no", []string{"nb", "nn"}},
	{"nrm", []string{"nrf", "fr"}},
	{"nyo", []string{"ttj", "nyn", "lg", "sw"}},
	{"oc", []string{"ca", "fr"}},
	{"olo", []string{"fi"}},
	{"os", []string{"ru"}},
	{"pcd", []string{"fr"}},
	{"pdc", []string{"de"}},
	{"pdt", []string{"de"}},
	{"pfl", []string{"de"}},
	{"pms", []string{"it"}},
	{"pnt", []string{"el"}},
	{"pt", []string{"pt-br"}},
	{"pt-br", []string{"pt"}},
	{"pwn", []string{"zh-tw", "zh-hant", "zh", "zh-hans"}},
	{"qu", []string{"qug", "es"}},
	{"qug", []string{"qu", "es"}},
	{"rgn", []string{"it"}},
	{"rm", []string{"de"}},
	{"rmy", []string{"ro"}},
	// Deprecated: Use 'rup' instead. See T17988.
	{"roa-rup", []string{"rup", "ro"}},
	{"roa-tara", []string{"it"}},
	{"rsk", []string{"sr-cyrl", "sr-ec"}},
	{"rue", []string{"uk", "ru"}},
	{"rup", []string{"ro"}},
	{"ruq", []string{"ruq-latn", "ro"}},
	{"ruq-cyrl", []string{"mk"}},
	{"ruq-latn", []string{"ro"}},
	{"rut", []string{"ru"}},
	{"sa", []string{"hi"}},
	{"sah", []string{"ru"}},
	{"scn", []string{"it"}},
	{"sdc", []string{"it"}},
	{"sdh", []string{"ckb", "fa"}},
	{"se", []string{"nb", "fi"}},
	{"se-fi", []string{"se", "fi", "sv"}},
	{"se-no", []string{"se", "nb", "nn"}},
	{"se-se", []string{"se", "sv"}},
	{"ses", []string{"fr"}},
	{"sg", []string{"fr"}},
	{"sgs", []string{"lt"}},
	{"sh", []string{"sh-latn", "sh-cyrl", "bs", "sr-latn", "sr-el", "hr"}},
	{"sh-cyrl", []string{"sr-cyrl", "sr-ec", "sh", "sh-latn"}},
	{"sh-latn", []string{"sh", "sh-cyrl", "bs", "sr-latn", "sr-el", "hr"}},
	{"shi", []string{"shi-latn", "fr"}},
	{"shy", []string{"shy-latn"}},
	{"shy-latn", []string{"fr"}},
	{"sjd", []string{"ru"}},
	{"sk", []string{"cs"}},
	{"skr", []string{"skr-arab"}},
	{"skr-arab", []string{"skr"}},
	{"sli", []string{"de"}},
	{"sma", []string{"sv", "nb"}},
	{"smn", []string{"fi"}},
	{"sr", []string{"sr-cyrl", "sr-ec", "sr-latn", "sr-el"}},
	{"sr-cyrl", []string{"sr-ec", "sr"}},
	{"sr-ec", []string{"sr-cyrl", "sr"}},
	{"sr-el", []string{"sr-latn", "sr"}},
	{"sr-latn", []string{"sr-el", "sr"}},
	{"srn", []string{"nl"}},
	{"sro", []string{"it"}},
	{"stq", []string{"de"}},
	{"sty", []string{"ru"}},
	{"su", []string{"id"}},
	{"szl", []string{"pl"}},
	{"szy", []string{"zh-tw", "zh-hant", "zh", "zh-hans"}},
	{"tay", []string{"zh-tw", "zh-hant", "zh", "zh-hans"}},
	{"tcy", []string{"kn"}},
	{"tet", []string{"pt"}},
	{"tg", []string{"tg-cyrl"}},
	{"tg-cyrl", []string{"tg"}},
	{"tg-latn", []string{"tg"}},
	{"trv", []string{"zh-tw", "zh-hant", "zh", "zh-hans"}},
	{"tt", []string{"tt-cyrl", "ru"}},
	{"ttj", []string{"nyo", "nyn", "lg", "sw"}},
	{"tt-cyrl", []string{"ru"}},
	{"ty", []string{"fr"}},
	{"tyv", []string{"ru"}},
	{"udm", []string{"ru"}},
	{"ug", []string{"ug-arab"}},
	{"vec", []string{"it"}},
	{"vep", []string{"et"}},
	{"vls", []string{"nl"}},
	{"vmf", []string{"de"}},
	{"vmw", []string{"pt"}},
	{"vot", []string{"fi"}},
	{"vro", []string{"et"}},
	{"wa", []string{"fr"}},
	{"wls", []string{"fr"}},
	{"wo", []string{"fr"}},
	{"wuu", []string{"wuu-hans", "wuu-hant", "zh-hans", "zh", "zh-hant"}},
	{"wuu-hans", []string{"wuu", "wuu-hant", "zh-hans", "zh", "zh-hant"}},
	{"wuu-hant", []string{"wuu", "wuu-hans", "zh-hant", "zh", "zh-hans"}},
	{"xal", []string{"ru"}},
	{"xmf", []string{"ka"}},
	{"yi", []string{"he"}},
	{"yue", []string{"yue-hant", "yue-hans"}},
	{"yue-hans", []string{"yue", "yue-hant"}},
	{"yue-hant", []string{"yue", "yue-hans"}},
	{"za", []string{"zh-hans", "zh", "zh-hant"}},
	// Deprecated: Use 'lzh' instead. See T30443.
	{"zh-classical", []string{"lzh", "zh-hant", "zh", "zh-hans"}},
	{"zh-cn", []string{"zh-hans", "zh", "zh-hant"}},
	{"zh-hans", []string{"zh-cn", "zh", "zh-hant"}},
	{"zh-hant", []string{"zh-tw", "zh-hk", "zh", "zh-hans"}},
	{"zh-hk", []string{"zh-hant", "zh-tw", "zh", "zh-hans"}},
	// Deprecated: Use 'nan' instead. See T30442.
	{"zh-min-nan", []string{"nan", "nan-latn-pehoeji", "nan-latn-tailo", "nan-hant", "cdo", "zh-hant", "zh", "zh-hans"}},
	{"zh-mo", []string{"zh-hk", "zh-hant", "zh-tw", "zh", "zh-hans"}},
	{"zh-my", []string{"zh-sg", "zh-hans", "zh-cn", "zh", "zh-hant"}},
	{"zh-sg", []string{"zh-hans", "zh-cn", "zh", "zh-hant"}},
	{"zh-tw", []string{"zh-hant", "zh-hk", "zh", "zh-hans"}},
	// Deprecated: Use 'yue' instead. See T30441.
	{"zh-yue", []string{"yue", "yue-hant", "yue-hans"}},
}

// fallbacksMap is the lazily built lookup map over languageFallbacks, so a
// query avoids a linear scan. A later entry for the same code wins.
//
//nolint:gochecknoglobals // built once
var fallbacksMap = sync.OnceValue(func() map[string][]string {
	m := make(map[string][]string, len(languageFallbacks))
	for _, f := range languageFallbacks {
		m[f.code] = f.fallbacks
	}
	return m
})

// getFallbacks returns the fallback languages for a language code, and false
// when the code has none.
func getFallbacks(lang string) ([]string, bool) {
	f, ok := fallbacksMap()[lang]
	return f, ok
}
