// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: frames.proto

// Frames as they travel a WebSocket between a bot and a client. It mirrors the
// frames.proto of the client SDKs: the package name, the message names and
// every field number match, so the wire format is compatible with any client
// built against them. Regenerate with:
//
//	go generate ./transport/wsserver/protobuf/internal/framepb

package framepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextFrame) Reset() {
	*x = TextFrame{}
	mi := &file_frames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextFrame) ProtoMessage() {}

func (x *TextFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextFrame.ProtoReflect.Descriptor instead.
func (*TextFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{0}
}

func (x *TextFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TextFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextFrame) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AudioRawFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Audio         []byte                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	NumChannels   uint32                 `protobuf:"varint,5,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"`
	Pts           *uint64                `protobuf:"varint,6,opt,name=pts,proto3,oneof" json:"pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioRawFrame) Reset() {
	*x = AudioRawFrame{}
	mi := &file_frames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRawFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRawFrame) ProtoMessage() {}

func (x *AudioRawFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRawFrame.ProtoReflect.Descriptor instead.
func (*AudioRawFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{1}
}

func (x *AudioRawFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioRawFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioRawFrame) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *AudioRawFrame) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioRawFrame) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *AudioRawFrame) GetPts() uint64 {
	if x != nil && x.Pts != nil {
		return *x.Pts
	}
	return 0
}

type TranscriptionFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionFrame) Reset() {
	*x = TranscriptionFrame{}
	mi := &file_frames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionFrame) ProtoMessage() {}

func (x *TranscriptionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionFrame.ProtoReflect.Descriptor instead.
func (*TranscriptionFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{2}
}

func (x *TranscriptionFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TranscriptionFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranscriptionFrame) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptionFrame) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TranscriptionFrame) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type MessageFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageFrame) Reset() {
	*x = MessageFrame{}
	mi := &file_frames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFrame) ProtoMessage() {}

func (x *MessageFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFrame.ProtoReflect.Descriptor instead.
func (*MessageFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{3}
}

func (x *MessageFrame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type InterruptionFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptionFrame) Reset() {
	*x = InterruptionFrame{}
	mi := &file_frames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptionFrame) ProtoMessage() {}

func (x *InterruptionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptionFrame.ProtoReflect.Descriptor instead.
func (*InterruptionFrame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptionFrame) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterruptionFrame) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*Frame_Text
	//	*Frame_Audio
	//	*Frame_Transcription
	//	*Frame_Message
	//	*Frame_Interruption
	Frame         isFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_frames_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frames_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frames_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetFrame() isFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *Frame) GetText() *TextFrame {
	if x != nil {
		if x, ok := x.Frame.(*Frame_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Frame) GetAudio() *AudioRawFrame {
	if x != nil {
		if x, ok := x.Frame.(*Frame_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *Frame) GetTranscription() *TranscriptionFrame {
	if x != nil {
		if x, ok := x.Frame.(*Frame_Transcription); ok {
			return x.Transcription
		}
	}
	return nil
}

func (x *Frame) GetMessage() *MessageFrame {
	if x != nil {
		if x, ok := x.Frame.(*Frame_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Frame) GetInterruption() *InterruptionFrame {
	if x != nil {
		if x, ok := x.Frame.(*Frame_Interruption); ok {
			return x.Interruption
		}
	}
	return nil
}

type isFrame_Frame interface {
	isFrame_Frame()
}

type Frame_Text struct {
	Text *TextFrame `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Frame_Audio struct {
	Audio *AudioRawFrame `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type Frame_Transcription struct {
	Transcription *TranscriptionFrame `protobuf:"bytes,3,opt,name=transcription,proto3,oneof"`
}

type Frame_Message struct {
	Message *MessageFrame `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type Frame_Interruption struct {
	Interruption *InterruptionFrame `protobuf:"bytes,5,opt,name=interruption,proto3,oneof"`
}

func (*Frame_Text) isFrame_Frame() {}

func (*Frame_Audio) isFrame_Frame() {}

func (*Frame_Transcription) isFrame_Frame() {}

func (*Frame_Message) isFrame_Frame() {}

func (*Frame_Interruption) isFrame_Frame() {}

var File_frames_proto protoreflect.FileDescriptor

const file_frames_proto_rawDesc = "" +
	"\n" +
	"\fframes.proto\x12\apipecat\"C\n" +
	"\tTextFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xac\x01\n" +
	"\rAudioRawFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05audio\x18\x03 \x01(\fR\x05audio\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\rR\n" +
	"sampleRate\x12!\n" +
	"\fnum_channels\x18\x05 \x01(\rR\vnumChannels\x12\x15\n" +
	"\x03pts\x18\x06 \x01(\x04H\x00R\x03pts\x88\x01\x01B\x06\n" +
	"\x04_pts\"\x83\x01\n" +
	"\x12TranscriptionFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\"\n" +
	"\fMessageFrame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"7\n" +
	"\x11InterruptionFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa4\x02\n" +
	"\x05Frame\x12(\n" +
	"\x04text\x18\x01 \x01(\v2\x12.pipecat.TextFrameH\x00R\x04text\x12.\n" +
	"\x05audio\x18\x02 \x01(\v2\x16.pipecat.AudioRawFrameH\x00R\x05audio\x12C\n" +
	"\rtranscription\x18\x03 \x01(\v2\x1b.pipecat.TranscriptionFrameH\x00R\rtranscription\x121\n" +
	"\amessage\x18\x04 \x01(\v2\x15.pipecat.MessageFrameH\x00R\amessage\x12@\n" +
	"\finterruption\x18\x05 \x01(\v2\x1a.pipecat.InterruptionFrameH\x00R\finterruptionB\a\n" +
	"\x05frameBOZMgithub.com/gojargo/jargo/transport/wsserver/protobuf/internal/framepb;framepbb\x06proto3"

var (
	file_frames_proto_rawDescOnce sync.Once
	file_frames_proto_rawDescData []byte
)

func file_frames_proto_rawDescGZIP() []byte {
	file_frames_proto_rawDescOnce.Do(func() {
		file_frames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frames_proto_rawDesc), len(file_frames_proto_rawDesc)))
	})
	return file_frames_proto_rawDescData
}

var file_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_frames_proto_goTypes = []any{
	(*TextFrame)(nil),          // 0: pipecat.TextFrame
	(*AudioRawFrame)(nil),      // 1: pipecat.AudioRawFrame
	(*TranscriptionFrame)(nil), // 2: pipecat.TranscriptionFrame
	(*MessageFrame)(nil),       // 3: pipecat.MessageFrame
	(*InterruptionFrame)(nil),  // 4: pipecat.InterruptionFrame
	(*Frame)(nil),              // 5: pipecat.Frame
}
var file_frames_proto_depIdxs = []int32{
	0, // 0: pipecat.Frame.text:type_name -> pipecat.TextFrame
	1, // 1: pipecat.Frame.audio:type_name -> pipecat.AudioRawFrame
	2, // 2: pipecat.Frame.transcription:type_name -> pipecat.TranscriptionFrame
	3, // 3: pipecat.Frame.message:type_name -> pipecat.MessageFrame
	4, // 4: pipecat.Frame.interruption:type_name -> pipecat.InterruptionFrame
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_frames_proto_init() }
func file_frames_proto_init() {
	if File_frames_proto != nil {
		return
	}
	file_frames_proto_msgTypes[1].OneofWrappers = []any{}
	file_frames_proto_msgTypes[5].OneofWrappers = []any{
		(*Frame_Text)(nil),
		(*Frame_Audio)(nil),
		(*Frame_Transcription)(nil),
		(*Frame_Message)(nil),
		(*Frame_Interruption)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frames_proto_rawDesc), len(file_frames_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frames_proto_goTypes,
		DependencyIndexes: file_frames_proto_depIdxs,
		MessageInfos:      file_frames_proto_msgTypes,
	}.Build()
	File_frames_proto = out.File
	file_frames_proto_goTypes = nil
	file_frames_proto_depIdxs = nil
}
